server:
  port: 8081

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/e-skylab

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

keycloak:
  auth-server-url: http://keycloak:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Super Skylab API
        url: /v3/api-docs/super-skylab

      - name: Forms API
        url: /v3/api-docs/formsapi

    oauth:
      client-id: swagger
      use-pkce-with-authorization-code-grant: true
      scopes:
        - openid
        - profile
        - email

    config-url: /v3/api-docs/swagger-config

  api-docs:
    enabled: true

  show-actuator: false